// Code generated by byctl. DO NOT EDIT.
package types

type BaseResponse struct {
	ErrorCode int    `json:"error_code"`
	ErrorMsg  string `json:"error_msg"`
}

type UpstreamListResponse struct {
	BaseResponse
	Upstreams []string `json:"upstreams"`
}

type MethodListResponse struct {
	BaseResponse
	List []Method `json:"list"`
}

type Method struct {
	Service string `json:"service"`
	Name    string `json:"name"`
}

type MethodListRequest struct {
	Upstream string `json:"upstream"`
}

type MethodDetailRequest struct {
	FullMethodName string `json:"full_method_name"`
}

type MethodDetailResponse struct {
	BaseResponse
	MethodName string    `json:"method_name"`
	ProtoDesc  string    `json:"proto_desc"`
	In         FieldItem `json:"in"`
	Out        FieldItem `json:"out"`
}

type FieldItem struct {
	Name      string `json:"name"`
	ProtoDesc string `json:"proto_desc"`
}

type CaseListRequest struct {
	TestedAppName string `json:"tested_app_name"`
}

type CaseListResponse struct {
	BaseResponse
	Cases []Case `json:"cases"`
}

type Case struct {
	TestedAppName string `json:"tested_app_name"`
	MethodName    string `json:"method_name"`
	Name          string `json:"name"`
	Rule          string `json:"rule, optional"`
	Body          string `json:"body"`
}

type CaseDelRequest struct {
	TestedAppName string `json:"tested_app_name"`
	MethodName    string `json:"method_name"`
	Name          string `json:"name"`
}

type CaseDelRespnse struct {
	BaseResponse
}

type CaseSetRequest struct {
	Cases []Case `json:"cases"`
}

type CaseSetResponse struct {
	BaseResponse
}

type CaseDetailRequest struct {
	TestedAppName string `json:"tested_app_name"`
	MethodName    string `json:"method_name"`
	Name          string `json:"name"`
}

type CaseDetailResponse struct {
	BaseResponse
	Detail Case `json:"detail"`
}

type UpstreamSetRequest struct {
	Upstreams []string `json:"upstreams"`
}

type UpstreamSetResponse struct {
	BaseResponse
}

type UpstreamDelRequest struct {
	Upstreams []string `json:"upstreams"`
}

type UpstreamDelResponse struct {
	BaseResponse
}

type AppListResponse struct {
	BaseResponse
	Apps []string `json:"apps"`
}

type AppDelRequest struct {
	Apps []string `json:"apps"`
}

type AppDelResponse struct {
	BaseResponse
}
